version: '3'

services:
  php-apache:
    build: ./docker/
    volumes:
      - ./:/var/www/html/
    ports:
      - "80:80"

  database:
    container_name: mysql_db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: MY_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "3306:3306"

volumes:
  db-data:
